name: hello
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  cached_network_image: 3.2.1
  camera: ^0.10.0+1
  clipboard: ^0.1.3
  country_picker: ^2.0.16
  country_pickers: ^2.0.0
  dio: ^4.0.6
  file_picker: ^5.0.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  get: 4.6.5
  group_radio_button: ^1.2.0
  image_cropper: ^3.0.0
  intl: ^0.17.0
  loading_overlay: ^0.3.0
  material_design_icons_flutter: 5.0.6996
  modal_bottom_sheet: ^2.1.2
  otp_text_field: ^1.1.3
  outline_search_bar: ^2.3.0
  path_provider: ^2.0.11
  #  url_launcher: 6.0.3
  streaming_shared_preferences: ^2.0.0
  story_view: ^0.13.2
  timeago: ^3.3.0
  wakelock: ^0.6.2
  web_socket_channel: ^2.2.0
  image_picker: ^0.8.7+3
  uuid: ^3.0.7
  share_plus: ^6.3.4

  # Video Player
  chewie: ^1.3.5
  video_thumbnail: ^0.5.3
  #  Firebase stuffs

  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3 # will satisfy your firebase core things that depend on ^4.5.1
  firebase_storage: ^11.2.3
  #  Notification stuffs
  awesome_notifications: ^0.6.19
  flutter_local_notifications: ^10.0.0-dev.3
  permission_handler: ^10.0.0
  #  Agora
  agora_rtc_engine: ^5.3.0
  # Background Service Stuffs
  flutter_background_service: ^2.3.5
  flutter_background_service_android: ^2.3.2
  audioplayers: ^0.20.1
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  carousel_slider: ^4.2.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - images/
    - assets/icons/
